apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app-blue
  labels:
    app: test-app
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-app
      version: blue
  template:
    metadata:
      labels:
        app: test-app
        version: blue
    spec:
      containers:
        - name: test-app-container
          image: rajeshdoddy/dockerimage01:latest
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: test-app
spec:
  selector:
    app: test-app
    version: blue  # Initially routing to Blue
  ports:
    - protocol: TCP
      port: 80          # External port
      targetPort: 80   # Port your app listens to internally
  type: LoadBalancer