apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app-green
  labels:
    app: test-app
    version: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-app
      version: green
  template:
    metadata:
      labels:
        app: test-app
        version: green
    spec:
      containers:
        - name: test-app
          image: ashokgcp6/dockerdemo:latest
          ports:
            - containerPort: 80